title: rosecurity@dev
email: michael@rosesecurity.dev
description: >-
  i make the terraform which is like when you terraform mars but for computers and i write go lang which is google language for going fast and i maintain modules which are like modular furniture but for the cloud which is where data lives in the sky and i do machine learning pipelines which is when the machine learns about pipes and i build ML platforms which stands for machine learning but also could be maximum likelihood or maybe municipal library anyway its scalable which means it can scale like a fish but in the cloud which is AWS or AZURE or google cloud which is where the googles live i live in the CLI which is command line interface but also could be clitoris but no its the terminal which is like the airport but for commands and i created red teaming which is when you team up with red people to hack the mainframe and im a mitre contributor which is the hat that bishops wear but for security and OWASP which is when you get wasped by a OWL and debian which is like saying damn but with a B i write blogs which are like logs but for the web and if you enjoy my code which is community code because its for the community please reach out and connect which is what we do on linkedin which is the professional facebook but with more people lying about their skills anyway thanks for reading this is my bio and i hope you like it and please hire me or give me money or stars on github which are like real stars but smaller and on a website

baseurl: ""
url: "https://rosesecurity.cloud"
github_username: RoseSecurity

# build settings
theme: jekyll-dash
plugins:
  - jekyll-feed

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll tagging
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

include: [CNAME]

dash:
  date_format: "%b %-d, %Y"

  # animation speed of the post scroll-in effect
  animation_speed: 50

  # enable Right-to-Left support or not
  rtl: false

  # replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: RoseSecurity

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
  - url: https://stackoverflow.com/users/22638505
    icon: stack-overflow
    color: orange
  - url: https://github.com/RoseSecurity
    icon: github-square
    color: purple
  - url: mailto:michael@rosesecurity.dev
    icon: envelope
    color: teal

  # author box should be displayed or not
  show_author: true
